### ISSUE TITLE
update gradle-node-plugin

### ISSUE THREAD

**Issue by samgqroberts** [ehirsch/gradle-react-plugin#4]
Hi,

It would be great to use the `nodeModulesDir` property of the gradle-node-plugin, but that's been added more recently (version 0.9) than the version that your plugin is using (version 0.7).  Could you upgrade the version of gradle-node-plugin to 0.9 please?

Thanks, all the best

**Comment by ehirsch** [comment]
Sure thing - I'll look into it.

**Comment by ehirsch** [comment]
Just released version 0.3.1 with the node-plugin-version bummed to 0.9. 
Let me know if everything works or if you need more help.
best
Eike

**Comment by samgqroberts** [comment]
thank you very much!

**Comment by ehirsch** [comment]
You're welcome.
