### ISSUE TITLE
Cannot find module 'jstransform/visitors/es6-arrow-function-visitors'

### ISSUE THREAD

**Issue by dasniko** [ehirsch/gradle-react-plugin#6]
Nice plugin, I like it!

I get an error when running the plugin in my project:

```
Error: Cannot find module 'jstransform/visitors/es6-arrow-function-visitors'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

After installing `npm install react-tools` in the project directory, the build with your plugin works like a charm. Perhaps you have to add some dependency to the plugin?
- regards

**Comment by dasniko** [comment]
BTW: I've just read, that react-tools are deprecated: https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html

Perhaps it's worth switching to use `Babel` in a new version of the plugin!?

**Comment by ehirsch** [comment]
Hi,
thanks for letting me know. I will look into both issues.

**Comment by ehirsch** [comment]
I finally was able to have a look…
The plugin should have warned you to install the react-tools. I can't why it hasn't. Can you recall anything from this issue and provide a way to reproduce it? (I know, it's been a while ;))

Concerning you Babel question: What would you prefer a pure 'babeled' jsx version or a full blown Babel plugin?

**Comment by dasniko** [comment]
Thanks for coming back on this... but, I finally switched to the gradle-node-plugin from SRS (which you are using also under the hood) to do all the NPM stuff. So I do a complete Babel transpile step before actual Java build/packaging and integrate it with my artifact.
Doing so allows me to use complete ES6 syntax, not only JSX transformation...
(in case you are curious in what I've done, have a look here: https://github.com/dasniko/ozark-react)
