### ISSUE TITLE
input file suffix

### ISSUE THREAD

**Issue by toobstar** [ehirsch/gradle-react-plugin#7]
Is it correct that this only processes .js files?  Could you also just process .jsx as well?

**Comment by ehirsch** [comment]
As of now this is the correct behaviour. But I guess it would be rather easy to configure an alternative extension. 
I'll try to make some time but you are welcome to provide a pull request ;)

The [JSXExtension](https://github.com/ehirsch/gradle-react-plugin/blob/master/src/main/groovy/net/eikehirsch/gradle/react/JSXExtension.groovy) would need to "learn" a new option ```fileExtension```. This new option has to be set at [JSXTask ```updateSettings```](https://github.com/ehirsch/gradle-react-plugin/blob/master/src/main/groovy/net/eikehirsch/gradle/react/JSXTask.groovy#L29) and used as an argument at  [JSXTask ```exec```](https://github.com/ehirsch/gradle-react-plugin/blob/master/src/main/groovy/net/eikehirsch/gradle/react/JSXTask.groovy#L50).

**Comment by ehirsch** [comment]
Just published version 0.4.1. It should be available as plugin in some minutes.
(I first had to remember how to publish this stuff ;)

**Comment by toobstar** [comment]
Thanks!
